//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCallServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodpreference
    {
        public int id { get; set; }
        public int subscriberid { get; set; }
        public int preferenceid { get; set; }
    
        public virtual foodtype foodtype { get; set; }
        public virtual subscriber subscriber { get; set; }
    }
}
