//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCallServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscriber()
        {
            this.foodpreferences = new HashSet<foodpreference>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string friendlyname { get; set; }
        public string phone { get; set; }
        public string deliveryaddress { get; set; }
        public Nullable<byte> emailoffers { get; set; }
        public Nullable<byte> textoffers { get; set; }
        public Nullable<byte> onmailinglist { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodpreference> foodpreferences { get; set; }
    }
}
