//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCallServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lastcallEntities : DbContext
    {
        public lastcallEntities()
            : base("name=lastcallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<foodoffer> foodoffers { get; set; }
        public virtual DbSet<foodpreference> foodpreferences { get; set; }
        public virtual DbSet<foodtype> foodtypes { get; set; }
        public virtual DbSet<subscriber> subscribers { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
    }
}
